platform :ios, '8.0'
pod 'AFNetworking', '~> 2.0'
pod 'SDWebImage', '~>3.7'
pod 'JSPatch'
pod 'Masonry'
pod 'MJExtension'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SVProgressHUD'
pod 'YLGIFImage'
pod 'MLPhotoBrowser', '~> 0.5.0'
pod 'AMap2DMap' #2D地图SDK
pod 'AMapSearch' #搜索服务SDK

platform :ios, '9.0'
pod 'EaseMobSDKFull'
